
import java.util.ArrayList;
import lightoff_chomienne_version_console.Chrono;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lunac
 */
public class fenetreVictoire extends javax.swing.JFrame {

    /**
     * Creates new form fenetreVictoire
     */
    
    
    public fenetreVictoire(int coups, String temps, Chrono temp) {
        initComponents();
        
        nbCoups.setText("Vous avez réalisé cette partie en "+ coups+ " coups.");
        if (temp.getDureeSec()<11){
            chrono.setText("Vif comme l'éclair! Vous avez mis "+temps+" à finir ce niveau.");;
        }
        if (temp.getDureeSec()<20 && temp.getDureeSec()>10){
            chrono.setText("Bien joué! Vous avez mis "+temps+" à finir ce niveau.");;;
        }
        if (temp.getDureeSec()>19){
            chrono.setText("Un peu longuet... Vous avez mis "+temps+" à finir ce niveau.");;
        }
       
        
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chrono = new javax.swing.JLabel();
        newPartie = new javax.swing.JButton();
        quitter = new javax.swing.JButton();
        nbCoups = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Bravo c'est gagné !");
        jLabel1.setToolTipText("");

        chrono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chrono.setForeground(new java.awt.Color(255, 0, 153));
        chrono.setText("jLabel2");

        newPartie.setBackground(new java.awt.Color(255, 204, 204));
        newPartie.setText("Rejouer");
        newPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPartieActionPerformed(evt);
            }
        });

        quitter.setBackground(new java.awt.Color(255, 204, 204));
        quitter.setText("Quitter");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });

        nbCoups.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nbCoups.setForeground(new java.awt.Color(255, 0, 153));
        nbCoups.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(newPartie)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quitter))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(156, 156, 156)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nbCoups, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chrono, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nbCoups)
                .addGap(18, 18, 18)
                .addComponent(chrono)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPartie)
                    .addComponent(quitter))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPartieActionPerformed
        // TODO add your handling code here:
        FenetreBienvenue f = new FenetreBienvenue();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newPartieActionPerformed

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quitterActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chrono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nbCoups;
    private javax.swing.JButton newPartie;
    private javax.swing.JButton quitter;
    // End of variables declaration//GEN-END:variables
}
